### ISSUE TITLE
TypeError in LimbDarkLightCurve

### ISSUE THREAD

**Issue by danhey** [exoplanet-dev/exoplanet#176]
**Describe the bug**
Hey all. I've finally gotten around to updating my version of exoplanet and am playing around with a few of the new case studies. I've been running into a strange TypeError:
`TypeError: Join cannot handle arguments of dimension 0. For joining scalar values, see @stack`
when calling `xo.LimbDarkLightCurve`. I am not sure why this is happening -- perhaps from a new version of PyMC3? 

**To Reproduce**
This occurs for  the case studies presented in "Putting it all together" and "Fitting TESS data". I've uploaded a notebook replicating this issue [here](https://gist.github.com/danhey/6a6b70494b8885816b82d575b98882ab), which shows the full error message.

**Expected behavior**
`xo.LimbDarkLightCurve` should return a light curve.

**Your setup (please complete the following information):**
 - Version of exoplanet: 0.4.5
 - Operating system: Manjaro Linux
 - Python version & installation method (pip, conda, etc.): Python 3.8 (also tested on Python 3.6). This happens to me through both pip and conda installations.
 - Theano: 1.1.2
 - PyMC3: 3.11.2

**Comment by dfm** [comment]
This is happening because you're running the case study for v0.5 (the unreleased GitHub version) but using the previous stable version. The syntax for passing limb darkening parameters has changed in the meantime. A few things that I need to do: 

- Make sure that the stable docs link to the stable case studies
- make sure that the version number is clear on the case studies page
- perhaps release a v0.4.6 that has a better error message

**Comment by danhey** [comment]
Cool, thanks Dan! I can confirm the reverted case studies are working now.

**Comment by dfm** [comment]
Great - thanks! I'm going to keep working on getting the versioning better with the case studies, but close this for now.
