### ISSUE TITLE
Is it possible to derive the orbital period of TESS single transit (without any additional transit observed)?

### ISSUE THREAD

**Issue by xylm2021** [exoplanet-dev/exoplanet#229]
As we know, we have detected a large number of TESS single transit events, and knowing their actual orbital period is never easy. I am wondering whether we can use machine learning to derive it, but it seems too complex for me at this stage. So could we use this package to do the same things? Or could we combine machine learning and MCMC to do this?

Our goal is without any RV observation data, just using the TESS single transit data and star information from TIC or GAIA to calculate a range for the possible orbital period. Thanks!

**Comment by dfm** [comment]
This isn't so much an `exoplanet` (the code) question, rather than a conceptual one. `exoplanet` does provide the tools that you'd need, but there are many subtleties when analyzing a single transit. These references might be useful:

- https://arxiv.org/abs/1607.08237
- https://arxiv.org/abs/1512.03722
- https://iopscience.iop.org/article/10.3847/2515-5172/aaf50c

And I'm sure there are others!

**Comment by xylm2021** [comment]
> This isn't so much an `exoplanet` (the code) question, rather than a conceptual one. `exoplanet` does provide the tools that you'd need, but there are many subtleties when analyzing a single transit. These references might be useful:
> 
> * https://arxiv.org/abs/1607.08237
> * https://arxiv.org/abs/1512.03722
> * https://iopscience.iop.org/article/10.3847/2515-5172/aaf50c
> 
> And I'm sure there are others!

OK, thanks!
